# Numpy

In [2]:
import numpy as np
from numpy import pi

a = np.array([[1, 2, 3], [4, 5, 6]], float)

print(a[0,1])
print(a[1, :])
print(a[:,2])
print(a[-1:,-2:])

2.0
[4. 5. 6.]
[3. 6.]
[[5. 6.]]


In [3]:
b = np.array(range(10), float)
print(b)

c = b.reshape((5,2))
print(c)
print(c.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
(5, 2)


In [4]:
a = np.array(range(6), float).reshape((2, 3))
print(a)
print(a.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [5]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b), axis=0))
print()
print(np.concatenate((a,b), axis=1))


[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [6]:
ide = np.identity(4, dtype=float)
print(ide)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
one_in_k = np.eye(4, k=1, dtype=float)
print(one_in_k)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [8]:
z = np.array([1,2,3,4,5,6,7,8,9], float)

print(z.sum())
print(z.prod())
print(z.mean())
print(z.var())
print(z.std())
print(z.min())
print(z.max())
print(z.argmin())
print(z.argmax())

45.0
362880.0
5.0
6.666666666666667
2.581988897471611
1.0
9.0
0
8


In [9]:
z = np.array([[9,5,4], [3,7,4], [5,6,2], [4,7,8]], float)
for (i, j, k) in z:
    print(i * j * k)
print()

print("Suma axis 0: ", z.sum(axis=0))
print("Suma axis 1: ", z.sum(axis=1))

print("Producto: ", z.prod())
print("Promedio axis 0:", z.mean(axis=0))
print("Promedio axis 1:", z.mean(axis=1))

print("Mediana: ", np.median(z))
print("Varianza: ", z.var())
print("Desciacion estadnar: ", z.std())

print(z.min())
print(z.max())
print(z.argmin()) # index
print(z.argmax())

print()
print("Coeficiente de correlacion: ", np.corrcoef(z))
print("Covarianza: ", np.cov(z))

180.0
84.0
60.0
224.0

Suma axis 0:  [21. 25. 18.]
Suma axis 1:  [18. 14. 13. 19.]
Producto:  203212800.0
Promedio axis 0: [5.25 6.25 4.5 ]
Promedio axis 1: [6.         4.66666667 4.33333333 6.33333333]
Mediana:  5.0
Varianza:  4.055555555555556
Desciacion estadnar:  2.0138409955990957
2.0
9.0
8
0

Coeficiente de correlacion:  [[ 1.         -0.54470478  0.45392065 -0.99862543]
 [-0.54470478  1.          0.5         0.5       ]
 [ 0.45392065  0.5         1.         -0.5       ]
 [-0.99862543  0.5        -0.5         1.        ]]
Covarianza:  [[ 7.         -3.          2.5        -5.5       ]
 [-3.          4.33333333  2.16666667  2.16666667]
 [ 2.5         2.16666667  4.33333333 -2.16666667]
 [-5.5         2.16666667 -2.16666667  4.33333333]]


# Random
Mersenne Twister algorithm

In [10]:
# set the seed
np.random.seed(293423)

x = np.random.rand(6).reshape((3,2))
print(x)

y = np.random.randint(5, 15)
print(y)

w = np.random.random()
print(w)

[[0.33677247 0.52693437]
 [0.79529578 0.78867702]
 [0.02147624 0.84612516]]
14
0.1526965000529379


# Ones & Zeros

In [11]:
zeros = np.zeros(10, dtype=int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


In [13]:
ones = np.ones((3, 5), dtype=int) # rows, cols
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
